"""
Core domain models for the backtesting engine.
"""

from dataclasses import dataclass, field
from datetime import date, datetime, time
from typing import Dict, Optional, Tuple


@dataclass(frozen=True)
class InstrumentMetadata:
    """Parsed metadata from an option instrument filename.

    Example: NIFTY22110318100CE
      → underlier=NIFTY, expiry=date(2022,11,3), strike=18100, option_type=CE
    """
    underlier: str
    expiry: date
    strike: int
    option_type: str  # "CE" or "PE"

    @property
    def name(self) -> str:
        """Reconstruct the instrument name."""
        return (
            f"{self.underlier}"
            f"{self.expiry.strftime('%y%m%d')}"
            f"{self.strike}"
            f"{self.option_type}"
        )

    def __str__(self) -> str:
        return self.name


@dataclass
class MarketSnapshot:
    """Complete market state at a single timestamp for one underlier.

    This is the fundamental unit of data flowing through the system.
    It contains the futures price and all available option prices
    at this moment.
    """
    timestamp: datetime
    underlier: str
    futures_price: float
    expiry: date
    available_strikes: list  # list of int
    option_prices: Dict[Tuple[int, str], float]  # (strike, opt_type) → price


@dataclass(frozen=True)
class Order:
    """An order generated by a strategy.

    Strategies produce orders; the execution handler consumes them.
    """
    timestamp: datetime
    instrument: InstrumentMetadata
    side: str  # "BUY" or "SELL"
    quantity: int
    execution_price: float
    reason: str = ""  # e.g. "roll", "eod_close", "entry"


@dataclass
class Position:
    """A currently held position in a single instrument.

    Tracks average entry price and provides MTM calculations.
    """
    instrument: InstrumentMetadata
    quantity: int
    average_price: float
    current_price: float
    entry_time: datetime

    @property
    def unrealized_pnl(self) -> float:
        """Mark-to-market unrealized PnL."""
        return (self.current_price - self.average_price) * self.quantity

    @property
    def market_value(self) -> float:
        """Current market value of this position."""
        return self.current_price * self.quantity


@dataclass(frozen=True)
class Trade:
    """A completed round-trip trade (entry + exit).

    Created when a position is closed.
    """
    entry_time: datetime
    exit_time: datetime
    instrument: InstrumentMetadata
    entry_price: float
    exit_price: float
    quantity: int
    transaction_costs: float

    @property
    def gross_pnl(self) -> float:
        """PnL before transaction costs."""
        return (self.exit_price - self.entry_price) * self.quantity

    @property
    def net_pnl(self) -> float:
        """PnL after transaction costs."""
        return self.gross_pnl - self.transaction_costs

    @property
    def holding_period_seconds(self) -> float:
        """Duration the position was held, in seconds."""
        return (self.exit_time - self.entry_time).total_seconds()
